### ISSUE TITLE
`toolbox:package:dependencies:install` command is failing in Linux without the --json argument

### ISSUE THREAD

**Issue by jeffreyazevedo** [ImJohnMDaniel/sfdx-toolbox-package-utils#8]
Starting sometime on 10/17/22, the `toolbox:package:dependencies:install` command started failing with the following error:

```
Retrieving packages currently installed in org....... done
Processing sfdx-project.json file... done

Package dependencies found for package directory force-app

dependentPackage == "TestPackage@0.1.0.2"
    04t1S000000262WQAQ : TestPackage@0.1.0.2
Analyzing dependencies to determine what needs to be installed.... done


Beginning installs of packages...

Installing package 04t1S000000262WQAQ : TestPackage@0.1.0.2
ERROR running toolbox:package:dependencies:install:  Cannot read properties of undefined (reading 'includes')
Installing packages....... done
```

However if you run the command with the `--json` argument for the same project it runs successfully:

```json
{
  "status": 0,
  "result": {
    "packagesInstalled": {
      "04t1S000000262WQAQ": {
        "dependentPackage": "TestPackage@0.1.0.2",
        "packageVersionId": "04t1S000000262WQAQ",
        "installationResult": {
          "attributes": {
            "type": "PackageInstallRequest",
            "url": "/services/data/v56.0/tooling/sobjects/PackageInstallRequest/0Hf0t0000006vGFCAY"
          },
          "Id": "0Hf0t0000006vGFCAY",
          "IsDeleted": false,
          "CreatedDate": "2022-10-19T13:48:07.000+0000",
          "CreatedById": "0050t00000AwHktAAF",
          "LastModifiedDate": "2022-10-19T13:48:07.000+0000",
          "LastModifiedById": "0050t00000AwHktAAF",
          "SystemModstamp": "2022-10-19T13:48:07.000+0000",
          "SubscriberPackageVersionKey": "04t1S000000262WQAQ",
          "NameConflictResolution": "Block",
          "SecurityType": "None",
          "PackageInstallSource": "U",
          "ProfileMappings": null,
          "Password": null,
          "EnableRss": false,
          "UpgradeType": null,
          "ApexCompileType": null,
          "Status": "SUCCESS",
          "Errors": null
        }
      }
    },
    "packagesNotInstalled": {}
  }
}
```

Here is the sfdx-project.json I'm using in a boilerplate sfdx project to install a simple test package:

```
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true,
      "dependencies": [
        {"package":  "TestPackage@0.1.0.2"}
      ],
      "package": "",
      "versionNumber": ""
    }
  ],
  "name": "Toolbox-JSON-issue",
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "55.0",
  "packageAliases": {
    "TestPackage@0.1.0.2": "04t1S000000262WQAQ"

  }
}
```

While adding the argument to the command is a workaround to the issue so you can install packages, it's less than ideal. When not asking for the results in json, you get a realtime progress indicator showing what package is currently being installed, and if it's not installed for some reason you get a verbose explanation (ex. `Package TestPackage@0.1.0.2 is already present in the org and will be ignored.`). 

However when using --json you only get the results after the entire command has completed and no explanation of why a package might not have been installed:

```json
{
  "status": 0,
  "result": {
    "packagesInstalled": {},
    "packagesNotInstalled": {
      "04t1S000000262WQAQ": {
        "dependentPackage": "TestPackage@0.1.0.2",
        "packageVersionId": "04t1S000000262WQAQ"
      }
    }
  }
}
```

Note that I'm encountering this issue in Linux (Ubuntu 20.04.4), but when I performed the same test in Windows the command worked successfully with and without the json argument.

**Comment by ImJohnMDaniel** [comment]
Please upgrade the plugin to version 0.8.4 and try again without the json flag.  Please let me know if that corrects the issue.

**Comment by ImJohnMDaniel** [comment]
This should be fixed now as of [commit 50386366](https://github.com/ImJohnMDaniel/sfdx-toolbox-package-utils/commit/503863663b9316a142cccea1cf1eab5024e2d5c4)

**Comment by jeffreyazevedo** [comment]
Thanks! This is working again without the json flag.

Though just a note that in my testing (and this may be an unrelated issue), I discovered that if a package install fails when run as a part of a CI build script, the error message is omitted. If you run the install command directly you'll see all of the output including the error message, but it would be great to be able to get that information as part of an overall build as well.

**Comment by ImJohnMDaniel** [comment]
> Though just a note that in my testing (and this may be an unrelated issue), I discovered that if a package install fails when run as a part of a CI build script, the error message is omitted. If you run the install command directly you'll see all of the output including the error message, but it would be great to be able to get that information as part of an overall build as well.

G'day @jeffreyazevedo -- Thanks for the feedback.  I am aware of that behavior and hope to have it corrected in the new version of the plugin that I am working on.  That one is still 2-3 months away though.  Cheers!
